services:
  filebrowser:
    container_name: filebrowser
    restart: unless-stopped
    image: 'filebrowser/filebrowser:s6'
    ports:
      - '8089:80'
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - filebrowser-data:/data
      - filebrowser-config:/config

volumes:
  filebrowser-data:
  filebrowser-config: